strictness: medium
test-warnings: true
doc-warnings: true
member-warnings: true
inherits:
  - default
  - full_pep8
ignore-paths:
  - docs/
  - ci/
  - example_videos/
  - maps/
  - scenarios/
  - tutorials
autodetect: false
max-line-length: 120

pycodestyle:
  run: true

pydocstyle:
  disable:
    - D100 #  exception should be removed
    - D104 # Missing docstring in public package
    - D203 # 1 blank line required before class docstring (Conflict with D211)
    - D212 # Multi-line docstring summary should start at the first line (Conflict with 213)
    - D407 # Missing dashed underline after section

pyflakes:
  run: true

mccabe:
  disable:
    - MC0001 # mccabe: MC0001 / CarlaPedestrianHandler.spawn is too complex (17), exception should be removed

pylint:
  disable:
    - import-error
    - too-many-branches
    - too-many-arguments
    - too-many-locals
    - too-many-statements
    - consider-using-f-string
    - missing-module-docstring
    - unsupported-assignment-operation

mypy:
  run: true
