
strictness: medium
test-warnings: true
doc-warnings: false
member-warnings: true
inherits:
  - default
  - full_pep8
ignore-paths:
  - docs/
autodetect: true
max-line-length: 120

pycodestyle:
    run: true

pydocstyle:
  disable:
    - D100 #  exception should be removed

pyflakes:
  run: true

mccabe:
  disable:
    - MC0001  # mccabe: MC0001 / CarlaPedestrianHandler.spawn is too complex (17), exception should be removed

pylint:
  disable:
    - import-error
    - too-many-branches
    - too-many-arguments
    - too-many-locals
    - too-many-statements
    - consider-using-f-string

mypy:
  run: true
