[tool.poetry]
name = "CommonRoad-Carla-Interface"
version = "0.0.1"
description = "Interface between CommonRoad and the traffic simulator CARLA."
authors = ["Cyber-Physical Systems Group, Technical University of Munich"]
license = "TODO"
readme = "README.md"
homepage = "https://commonroad.in.tum.de"
keywords= ["autonomous", "automated", "vehicles", "driving", "motion", "planning", "simulation"]
classifiers = [
    "Programming Language :: Python :: 3.8",
    "License :: OSI Approved :: BSD License",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows"
]
packages = [{include = "carlacr"}]

#[tool.poetry.urls]
#Documentation = "https://commonroad.in.tum.de/static/docs/commonroad-io/index.html"
#Forum = "https://commonroad.in.tum.de/forum/c/commonroad-io"
#Source = "https://gitlab.lrz.de/tum-cps/commonroad_io"


[tool.poetry.dependencies]
python = "^3.8"
numpy = ">=1.2"
pygame = ">=2.1.2"
commonroad-io = ">=2022.3"
imageio = "~=2.9.0"
scipy = ">=1.2.0"
carla = "~0.9.13"
moviepy = "~=1.0.3"
lxml = ">=4.8.0"
omegaconf = ">=2.1.2"
typing = "~=3.7.4.3"
typer = ">=0.4.0"
matplotlib = "~=3.5.2"
commonroad-scenario-designer = "~=0.6.1"
commonroad-drivability-checker = "~=2022.2.1"
commonroad-vehicle-models = "~=3.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
