carla_parameters:
  host: localhost  # carla host setting
  port: 2000  # carla default port setting
  sleep_time: 5 # time to move your view in carla-window

carla_root_path: /opt/carla-simulator/
#if you are using Windows, please adapt the path to carla local installation here at carla_root_path



