image: "python:3.8"

stages:
  - static_check
  - test
  - build

before_script:
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .

.install-and-run: &install-and-run
  - pip install tox coverage
  - coverage run --source ./ -m unittest tests/run_tests.py
  - coverage report -m --omit="*/src/*,*/tests/*" || true

# static_check
prospector_source:
  stage: static_check
  image: "python:3.8"
  script:
    - python -m pip install prospector[with_mypy]
    - prospector carlacr/

#prospector_test:
#  stage: static_check
#  image: "python:3.8"
#  script:
#    - python -m pip install prospector[with_mypy]
#    - prospector tests/
#
#prospector_tutorials:
#  stage: static_check
#  image: "python:3.8"
#  script:
#    - python -m pip install prospector[with_mypy]
#    - prospector tutorials/

# test
#build_test_python_3_8:
#  image: "python:3.8"
#  stage: test
#  script:
#    - *install-and-run

# build


#build_package_py_38:
#    stage: build
#    image: "python:3.8"
#    script:
#        - poetry build


docs_py_38:
  image: "python:3.8"
  stage: build
  script:
    - pip install -r ./docs/doc_requirements.txt
    - cd docs && bash ./setup.sh
  artifacts:
    paths:
      - ./docs/build/
